### ISSUE TITLE
Publish the code as ES5 ?

### ISSUE THREAD

**Issue by kerphi** [sindresorhus/pretty-bytes#43] opened 2018-03-21 21:54 UTC
I am using the pretty-bytes package in a frontend reactjs application (using create-react-app for building)
I just got this error when doing "npm run build" on my application:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/pretty-bytes/index.js:4 

Read more here: http://bit.ly/2tRViJ9
```

Would it be possible to publish this great pretty-bytes code on NPM with the ES5 syntaxe?

**Comment by sindresorhus** [comment] 2018-03-22 03:46
Duplicate of #42

**Closed by sindresorhus** 2018-03-22 03:46 UTC
