### ISSUE TITLE
Unexpected token: operator (>)

### ISSUE THREAD

**Issue by espiegel** [sindresorhus/pretty-bytes#30] opened 2017-02-28 23:40 UTC
With webpack i'm getting the following error:

```
ERROR in app.aa267055ad0890445649.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/pretty-bytes/index.js:4,0]
```

Does this library have to use es6? Doesn't seem like its essential.

**Comment by sindresorhus** [comment] 2017-03-01 01:33
Duplicate of https://github.com/sindresorhus/pretty-bytes/issues/29.

**Closed by sindresorhus** 2017-03-01 01:33 UTC

**Comment by SamVerschueren** [comment] 2017-03-01 06:48
You can still use `3.0.1` though.

**Comment by espiegel** [comment] 2017-03-02 17:58
@SamVerschueren thanks!
